### PR TITLE
Adding Programs from LeetCode Daily Challenge

### PR DESCRIPTION
**Pull request by Abiji-2020**

### CODE REVIEW

**Comment by dhruvabhat24** [comment]
@Abiji-2020 This repo is only for leetcode study plans 
If you want to contribute on daily challenge then create a pull request on Leetcode 2024 repository
Usually I will add Java codes if you would like to contribute in another language them u can

**Comment by dhruvabhat24** [comment]
You can close the pull request here

**Comment by dhruvabhat24** [comment]
https://github.com/dhruvabhat24/Leetcode-2024
This is the repo link 🔗

**Comment by Abiji-2020** [comment]
Ok I will be mostly doing my problems in C++ so I will be contributing it to that thanks for sharing the repo of Daily Challenges

**Pull request closed without merging**
